"""Shared pipeline state structures for backscatter processing."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np


@dataclass
class BackscatterPipelineState:
    """Container for intermediate artifacts generated by the backscatter pipeline."""

    calibrated_subswaths: Dict[str, np.ndarray] = field(default_factory=dict)
    pipeline_results: List[Dict[str, Any]] = field(default_factory=list)
    primary_subswath: Optional[str] = None
    working_data: Optional[np.ndarray] = None
    geocoded_data: Optional[np.ndarray] = None
    geocode_valid_percentage: Optional[float] = None
    db_data: Optional[np.ndarray] = None
    valid_pixel_count: Optional[int] = None
    total_pixels: Optional[int] = None
    valid_percentage: Optional[float] = None
    export_records: List[Dict[str, Any]] = field(default_factory=list)
