name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev gdal-bin
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest numpy rasterio pyproj
    
    - name: Check Rust formatting
      run: cargo fmt -- --check
    
    - name: Run Rust clippy
      run: cargo clippy -- -D warnings
    
    - name: Run Rust tests
      run: cargo test --release
    
    - name: Build Python package
      run: maturin develop --release
    
    - name: Run Python tests
      run: pytest tests/ -v
